config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :games do
    resources :titles
    resources :matches
  end

  root 'players#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, presence: true

  has_many :titles, -> { order(:rank) }
  has_many :matches, -> { order(updated_at: :desc) }
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :game

  has_many :match_players
  has_many :players, through: :match_players

  accepts_nested_attributes_for :match_players

  validates :match_players, length: { minimum: 2 }
end

app/models/match_player.rb
class MatchPlayer < ApplicationRecord
  belongs_to :match
  belongs_to :player

  validates :rank, presence: true, numericality: { greater_than: 0 }

  default_scope { order(rank: :asc) }
end

app/models/player.rb
class Player < ApplicationRecord
  validates :discord_id, presence: true
  validate :verify_discord_id, on: :create

  has_many :match_players
  has_many :matches, through: :match_players
  has_many :games, through: :matches

  def profile
    Profile.new(discord_id)
  end

private

  def verify_discord_id
    profile.name
  rescue
    errors.add(:discord_id, 'Invalid discord id')
  end
end

app/models/profile.rb
class Profile
  include ActiveModel::Model

  USER_ENDPOINT = 'https://canary.discord.com/api/v8/users/%{id}'.freeze
  DISCORD_CDN = 'https://cdn.discordapp.com/avatars/%{id}/%{avatar_hash}.jpg'.freeze

  def initialize(id)
    @id = id
  end

  def name
    attributes.fetch(:username)
  end

  def avatar
    DISCORD_CDN % { id: @id, avatar_hash: attributes.fetch(:avatar) }
  end

private

  def attributes
    @attributes ||= load_attributes
  end

  def load_attributes
    http_client = Net::HTTP.new(endpoint.host, endpoint.port)
    http_client.use_ssl = true
    http_client.verify_mode = OpenSSL::SSL::VERIFY_PEER
    info_request = Net::HTTP::Get.new(endpoint.request_uri)
    info_request['Authorization'] = "Bot #{Rails.application.credentials.discord[:token]}"
    JSON.parse(http_client.request(info_request).body).symbolize_keys
  end

  def endpoint
    @endpoint ||= URI(USER_ENDPOINT % { id: @id })
  end
end

app/models/title.rb
class Title < ApplicationRecord
  validates :rank, :name, :game, presence: true
  validates :rank, numericality: { greater_than: 0 }

  belongs_to :game

  def self.next_free_rank
    (last&.rank || 0).next
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.order(updated_at: :desc)
  end

  def show
    @game = Game.find(params.require(:id))
    @recent_matches = @game.matches.limit(3).includes(match_players: :player)
  end

  def new
    @game = Game.new
  end

  def create
    Game.create!(params.require(:game).permit(:name))
    redirect_to games_path
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
    @game = e.try(:record) || Game.new
    render action: :new
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new
    game = Game.find(params.require(:game_id))
    template = game.matches.first
    @match = Match.new
  end

  def create
    Match.create!(create_params)
    redirect_to game_path(id: params.require(:game_id))
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
    @match = e.try(:record) || Match.new
    render :edit
  end

private

  def create_params
    params.require(:match)
    .permit(match_players_attributes: %i[player_id rank])
    .merge(game_id: params.require(:game_id))
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    Player.create!(params.require(:player).permit(:discord_id))
    redirect_to players_path
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
    @player = e.try(:record) || Player.new
    render action: :new
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
    @game = Game.find(params.require(:game_id))
    @titles = @game.titles
  end

  def new
    game = Game.find(params.require(:game_id))
    @title = Title.new(rank: game.titles.next_free_rank)
    render :edit
  end

  def edit
    @title = Title.find(params.require(:id))
  end

  def create
    create_params = params.require(:title).permit(:name, :rank)
    Title.create!(create_params.merge(params.permit(:game_id)))
    redirect_to game_titles_path
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
    @title = e.try(:record) || Title.new
    render :edit
  end

  def update
    @title = Title.find(params.require(:id))
    @title.update(params.require(:title).permit(:name, :rank))
    redirect_to game_titles_path(game_id: @title.game_id)
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
    @title = e.try(:record) || @title
    render :edit
  end

  def destroy
    title = Title.find(params.require(:id)).destroy!
    redirect_to game_titles_path(game_id: title.game_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_game.haml
= link_to(game.name, game_path(game))

app/views/games/index.haml
.flex.justify-between.items-center.w-100
  %h1 Games
  = link_to('Create', new_game_path)

.ma2.center.flex.flex-column.w-100.justify-center
  = @games.present? ? render(@games) : 'No games yet...'

app/views/games/new.haml
%h1 Create Game
- if @game.errors.any?
  %p.red.b Failed to create game, does it already exist?

= form_with(model: @game) do |form|
  = form.label(:name)
  = form.text_field(:name, required: true)
  .flex.flex-wrap.items-center
    = link_to('Back', games_path)
    = form.submit('Create')

app/views/games/show.haml
.flex.justify-between.items-center.w-100
  %h1 
    = @game.name
  = link_to('Back', games_path)

.flex.w-100.items-center.spaced-children
  = link_to('Record Match', new_game_match_path(game_id: @game.id))
  = link_to('Titles', game_titles_path(game_id: @game.id))

%h2 Standings

%h2 Recent Matches

= render(@recent_matches)

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
  %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
  %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
  %title Ladder Matches
  = csrf_meta_tags
  = csp_meta_tag
  = javascript_pack_tag 'application'
  = stylesheet_pack_tag 'stylesheet', media: 'all'
  %link{ href: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap', rel: 'stylesheet' }
%body.bg-lightest-blue
  %header.w-100.pa2.f6.fw3.flex.justify-end
    - %i[players games].each do |resource|
      = link_to(resource, try(:"#{resource}_path"), class: 'mh2')
  .center.w-100.mw8.ba.b--dark-gray.bg-white.pv4.ph5.ma4
    = yield

app/views/match_players/_match_player.haml
.w-100
  = render(match_player.player)

app/views/matches/_match.haml
%h3
  Match
  = match.updated_at.strftime('%-d/%-m/%y')
.flex.w-100.items-center
  = render(match.match_players)

app/views/matches/new.haml
%h1 
  Record Match

- if @match.errors.any?
  %p.red.b Failed :(

= form_with(model: [:game, @match]) do |form|

  = react_component('matches/MatchRankingInput', matchPlayers: @match.match_players)

  .flex.flex-wrap.items-center
    = link_to('Back', game_titles_path(game_id: params.require(:game_id)))
    = form.submit('Record')

app/views/players/_player.haml
- cache player do
  .mw6.w-100.ma3
    = render(player.profile)

app/views/players/index.haml
.flex.justify-between.items-center.w-100
  %h1 Players
  = link_to('Create', new_player_path)

.ma2.center.flex.flex-wrap.w-100.justify-center
  = @players.present? ? render(@players, cached: true) : 'No players yet...'

app/views/players/new.haml
%h1 Create Player
- if @player.errors.any?
  %p.red.b Failed to create player, please check your discord id is correct.

= form_with(model: @player) do |form|
  = form.label(:discord_id, 'Discord User Id')
  = form.number_field(:discord_id, required: true)
  .flex.flex-wrap.items-center
    = link_to('Back', players_path)
    = form.submit('Create')

app/views/profiles/_profile.haml
.flex.items-center.ba.b--moon-gray.pa3
  = image_tag(profile.avatar, class: 'w3 h3 br-100 ba b--dark-gray')
  %h3.mv0.ml3.navy
    = profile.name

app/views/titles/_title.haml
%li.w-100.flex.justify-between.items-center
  %p.mr3
    = title.rank
  %p.flex-auto
    = title.name
  = link_to('edit', edit_game_title_path(id: title.id))
  = button_to('delete', game_title_path(id: title.id), method: :delete, class: 'button')

app/views/titles/edit.haml
- action = @title.persisted? ? 'Change' : 'Create'
%h1 
  = action
  Title

- if @title.errors.any?
  %p.red.b Failed :(

= form_with(model: [:game, @title]) do |form|
  = form.label(:rank)
  = form.number_field(:rank, required: true, min: 1)

  = form.label(:name)
  = form.text_field(:name, required: true)

  .flex.flex-wrap.items-center
    = link_to('Back', game_titles_path(game_id: params.require(:game_id)))
    = form.submit(action)

app/views/titles/index.haml
.flex.justify-between.items-center.w-100
  %h1
    = link_to(@game.name, game_path(@game))
    > Titles
  = link_to('Create', new_game_title_path)

%ol.ma2.center.flex.flex-wrap.w-100.justify-center
  = @titles.present? ? render(@titles) : 'No titles yet...'